version: "3"
services:
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    pid: "host"
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /usr/local/redis/data /usr/local/redis/log
        touch /usr/local/redis/log/redis.log /usr/local/redis/data/appendonly.aof
        chmod -R 665 /usr/local/redis/
        redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - /usr/local/redis/data:/usr/local/redis/data:rw
      - /usr/local/redis/log:/usr/local/redis/log:rw

  mysql:
    image: mysql:5.7.12
    container_name: mysql
    ports:
      - "3017:3017"
    restart: always
    pid: "host"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /etc/conf/my.cnf:/etc/mysql/my.cnf:rw
      - /usr/local/mysql/log:/usr/local/mysql/log:rw
      - /usr/local/mysql/data:/usr/local/mysql/data:rw

  mongo:
    mongo:
    image: mongo:3.6.5
    container_name: mongo
    ports:
      - "23010:23010"
    restart: always
    pid: "host"
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /usr/local/mongodb/data /usr/local/mongodb/log
        chmod -R 666 /usr/local/mongodb/data /usr/local/mongodb/log
        mongod -f /etc/mongod.conf                           
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /etc/conf/mongod.conf:/etc/mongod.conf:rw
      - /usr/local/mongodb/log:/var/log/mongodb:rw
      - /usr/local/mongodb/data:/var/lib/mongodb:rw
 
  zk:
    image: zookeeper:3.4.11
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    restart: always
    pid: "host"
    environment:
      ZOO_MY_ID: 1
    volumes:
      - /usr/local/zookeeper/data:/data:rw
      - /usr/local/zookeeper/log:/datalog:rw
      - /etc/conf/zoo.cfg:/conf/zoo.cfg:rw
    
  activemq:
    image: rmohr/activemq:5.15.3
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    restart: always
    pid: "host"
    
  emqtt:
    image: emqttd-docker-v2.3.10:latest
    container_name: emqtt
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    restart: always
    pid: "host"
    
networks:
  frontend:
  backend:

volumes:
  db-data: